{% set name = "cmomy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmomy-{{ version }}.tar.gz
  sha256: e0b79d0866809d4b636543fd4f5413c61df9a26dfd0f874002799988199847d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - numba >=0.50
    - xarray >=0.16
    - typing-extensions
    - docstring-inheritance
    - module-utilities >=0.6
    - lazy_loader

test:
  imports:
    - cmomy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/cmomy
  summary: Central (co)moment calculation/manipulation
  description: |
    A Python package to calculate and manipulate Central (co)moments.
    The main features of `cmomy` are 1) Fast calculation of central
    moments and comoments with weights.  The speed comes from using
    Numba.  2) Support for scalar and vector inputs. 3) Numpy and
    xarray DataArray interface. 4) Resampling.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
