{% set name = "cmomy" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmomy-{{ version }}.tar.gz
  sha256: 2b04dbcafa49cadffab15e0d8b1c7fadcca5096d965f28e9ecaad8305ab6b5b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - numba >=0.50
    - xarray >=0.16
    - typing-extensions
    - custom-inherit
    - module-utilities >=0.1

test:
  imports:
    - cmomy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/cmomy
  summary: Central (co)moment calculation/manipulation
  description: |
    Central (co)moment calculation/manipulation
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - usnistgov
