{% set name = "cmomy" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmomy-{{ version }}.tar.gz
  sha256: f96676752b3ee22c068dfea49e122488cd32c53a368b11b2b8a9979181d6e5ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - setuptools >=61.2
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8,<3.11
    - numpy >=1.20,<1.24
    - numba >=0.50
    - xarray >=0.16
    - typing-extensions
    - custom-inherit
    - module-utilities >=0.1

test:
  imports:
    - cmomy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/cmomy
  summary: Central (co)moment calculation/manipulation
  description: |
    A Python package to calculate and manipulate Central (co)moments.
    The main features of `cmomy` are 1) Fast calculation of central
    moments and comoments with weights.  The speed comes from using
    Numba.  2) Support for scalar and vector inputs. 3) Numpy and
    xarray DataArray interface. 4) Resampling.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
